name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out my other private repo
      uses: actions/checkout@master
    - name: checkout
      uses: siva1024/scp-deployer@latest
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.KEY }}
        pub: ${{ secrets.PUB }}
        source: |
          './test/*' => /home/github/test/
          ./test/test1* => $TARGET_DIR/test1/
          ./test/test*.csv => "/home/github/test/test2/"
        target: "test"
 
